version: "3.8"
services:
  message-broker:
    image: rabbitmq:3.12.10
    ports:
      - "5672:5672"
      - "15672:15672"

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    restart: always

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    restart: always

  resource-processor:
    build: ./resource-processor
#    ports:
#      - "5556:5556"
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5556"
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    restart: always
    deploy:
      replicas: 3
    depends_on:
      - message-broker
      - discovery-service
      - song-service

  resource-service:
    build: ./resource-service
    ports:
      - "7080:8080"
#      port for debug
      - "5555:5555"
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5555"
      - DATABASE_URL=jdbc:postgresql://resource-service-database:5432/${RESOURCE_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${RESOURCE_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${RESOURCE_SERVICE_DATABASE_PASSWORD}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    depends_on:
      - discovery-service
      - resource-service-database
      - song-service
      - localstack

  song-service:
    build: ./song-service
    #    ports enabled for test reasons
#    ports:
#      - "7081:8080"
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5555"
      - DATABASE_URL=jdbc:postgresql://song-service-database:5432/${SONG_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${SONG_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${SONG_SERVICE_DATABASE_PASSWORD}
      - EUREKA_CLIENT_URL=${SERVICE_DISCOVERY_URL}
    restart: always
    deploy:
      replicas: 3
    depends_on:
      - discovery-service
      - song-service-database

  resource-service-database:
    image: postgres:16.1-bullseye
    #    ports enabled for test reasons
    ports:
      - "7432:5432"
    volumes:
      - resource-service-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${RESOURCE_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${RESOURCE_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${RESOURCE_SERVICE_DATABASE_PASSWORD}

  song-service-database:
    image: postgres:16.1-bullseye
    #    ports enabled for test reasons
    ports:
      - "8432:5432"
    volumes:
      - song-service-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SONG_SERVICE_DATABASE_NAME}
      - POSTGRES_USER=${SONG_SERVICE_DATABASE_USER}
      - POSTGRES_PASSWORD=${SONG_SERVICE_DATABASE_PASSWORD}
volumes:
  resource-service-database:
  song-service-database:
