server:
  port: 7084
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:7004/resources
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my:
  client:
    song-service:
      scheme: http
      host: localhost
      port: 7083
      endpoint: ping
