server:
  error:
    include-stacktrace: never
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my:
  client:
    song-service:
      scheme: http
      host: song-service
      port: 8080
      endpoint: songs
    s3:
      url: http://localstack:4566  # Need this only because of the localhost
      accessKey: fake_access_key  # Any value is accepted by the S3Client and by the localstack
      secretKey: fake_secret_key  # Any value is accepted by the S3Client and by the localstack
      bucket: com.hrm.my.bucket.1 # Should be unique across all AWS S3 Buckets globally (locally for localstack)
      region: us-west-1           # Any value is accepted by the S3Client and by the localstack

